package com.course.aftersales.service;

import com.course.aftersales.repository.Database;
import java.sql.*;
import java.time.*;
import java.util.*;

public class AdminService {
    private final EngineerApplicationService applicationService = new EngineerApplicationService();
    public Map<String,Object> data()throws Exception{
        Map<String,Object>d=new HashMap<>();try(Connection c=Database.open()){
            d.put("users",Database.query(c,"SELECT u.*,ep.qualification_status,ep.employment_status FROM system_user u LEFT JOIN engineer_profile ep ON ep.engineer_id=u.user_id ORDER BY u.user_id"));
            d.put("configs",Database.query(c,"SELECT sc.*,u.display_name updated_name FROM system_config sc LEFT JOIN system_user u ON u.user_id=sc.updated_by ORDER BY sc.config_key"));
            d.put("devices",Database.query(c,"SELECT * FROM device_type ORDER BY device_type_id"));d.put("faults",Database.query(c,"SELECT f.*,d.name device_name FROM fault_type f JOIN device_type d ON d.device_type_id=f.device_type_id ORDER BY f.fault_type_id"));d.put("areas",Database.query(c,"SELECT * FROM service_area ORDER BY service_area_id"));d.put("slots",Database.query(c,"SELECT * FROM standard_time_slot ORDER BY start_time"));
            d.put("exceptions",Database.query(c,"SELECT a.appointment_id,a.appointment_no,a.status,a.cancel_reason,a.updated_at,cu.display_name customer_name,eu.display_name engineer_name FROM appointment a JOIN system_user cu ON cu.user_id=a.customer_id JOIN system_user eu ON eu.user_id=a.engineer_id WHERE a.status IN ('PENDING_RESCHEDULE','EXPIRED') ORDER BY a.updated_at DESC"));
            d.put("logs",Database.query(c,"SELECT l.*,u.display_name FROM operation_log l LEFT JOIN system_user u ON u.user_id=l.user_id ORDER BY l.created_at DESC LIMIT 80"));
            d.put("stats",Database.query(c,"SELECT '预约总数' metric,COUNT(*) metric_value FROM appointment UNION ALL SELECT '完成工单',COUNT(*) FROM repair_order WHERE order_status='COMPLETED' UNION ALL SELECT '配件申请',COUNT(*) FROM part_request UNION ALL SELECT '有效评价',COUNT(*) FROM review WHERE status='VALID'"));
            d.put("applications",applicationService.applications(c));
            d.put("applicationSkills",applicationService.applicationSkills(c));
        }return d;
    }
    public void setUserStatus(long admin,long userId,String status)throws Exception{if(!Arrays.asList("ACTIVE","DISABLED").contains(status))throw new IllegalArgumentException("用户状态无效");try(Connection c=Database.open()){if(userId==admin&&"DISABLED".equals(status))throw new IllegalArgumentException("不能停用当前管理员账号");Database.update(c,"UPDATE system_user SET status=? WHERE user_id=?",status,userId);log(c,admin,"SET_USER_STATUS","USER",userId,status);}}
    public void setQualification(long admin,long engineerId,String status)throws Exception{if(!Arrays.asList("APPROVED","EXPIRED","PENDING").contains(status))throw new IllegalArgumentException("资质状态无效");try(Connection c=Database.open()){Database.update(c,"UPDATE engineer_profile SET qualification_status=? WHERE engineer_id=?",status,engineerId);log(c,admin,"SET_QUALIFICATION","ENGINEER",engineerId,status);}}
    public void updateConfig(long admin,String key,String value)throws Exception{if(key.isEmpty()||value.isEmpty())throw new IllegalArgumentException("配置键和值不能为空");try(Connection c=Database.open()){int n=Database.update(c,"UPDATE system_config SET config_value=?,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE config_key=?",value,admin,key);if(n==0)Database.insert(c,"INSERT INTO system_config(config_key,config_value,description,updated_by) VALUES(?,?,?,?)",key,value,"管理员新增参数",admin);log(c,admin,"UPDATE_CONFIG","CONFIG",0,key+"="+value);}}
    public void addBasic(long admin,String kind,String name,long parent,String start,String end)throws Exception{if(name.isEmpty())throw new IllegalArgumentException("名称不能为空");try(Connection c=Database.open()){long id;if("device".equals(kind))id=Database.insert(c,"INSERT INTO device_type(name,status) VALUES(?,'ACTIVE')",name);else if("fault".equals(kind)){if(parent<=0)throw new IllegalArgumentException("故障类别必须选择设备类别");id=Database.insert(c,"INSERT INTO fault_type(device_type_id,name,status) VALUES(?,?,'ACTIVE')",parent,name);}else if("area".equals(kind))id=Database.insert(c,"INSERT INTO service_area(name,status) VALUES(?,'ACTIVE')",name);else if("slot".equals(kind)){if(start.isEmpty()||end.isEmpty())throw new IllegalArgumentException("标准时段需要开始和结束时间");id=Database.insert(c,"INSERT INTO standard_time_slot(name,start_time,end_time,status) VALUES(?,?,?,'ACTIVE')",name,Time.valueOf(start+":00"),Time.valueOf(end+":00"));}else throw new IllegalArgumentException("基础数据类型无效");log(c,admin,"ADD_BASIC_DATA",kind.toUpperCase(),id,name);}}
    public void reviewApplication(long admin,long applicationId,boolean approve,String comment)throws Exception{applicationService.review(admin,applicationId,approve,comment);}
    public int expireReschedules(final long admin)throws Exception{
        final int[] count={0};Database.tx(c->{int hours=config(c,"RESCHEDULE_HOURS",24);Timestamp threshold=Timestamp.valueOf(LocalDateTime.now().minusHours(hours));List<Map<String,Object>> rows=Database.query(c,"SELECT a.appointment_id,ro.order_id,a.customer_id FROM appointment a JOIN repair_order ro ON ro.appointment_id=a.appointment_id WHERE a.status='PENDING_RESCHEDULE' AND a.updated_at<?",threshold);for(Map<String,Object>r:rows){long id=((Number)r.get("appointment_id")).longValue();Database.update(c,"UPDATE appointment SET status='EXPIRED',updated_at=CURRENT_TIMESTAMP WHERE appointment_id=?",id);Database.update(c,"UPDATE repair_order SET order_status='CANCELLED' WHERE order_id=?",r.get("order_id"));Database.update(c,"INSERT INTO appointment_change(appointment_id,change_type,old_status,new_status,operator_id,reason) VALUES(?,'RESCHEDULE_TIMEOUT','PENDING_RESCHEDULE','EXPIRED',?,'待改约超过系统配置时限')",id,admin);notify(c,((Number)r.get("customer_id")).longValue(),"RESCHEDULE_EXPIRED","待改约预约已过期","预约因超过改约时限已关闭","APPOINTMENT",id);count[0]++;}log(c,admin,"EXPIRE_RESCHEDULES","SYSTEM",0,"处理数量："+count[0]);});return count[0];
    }
    public int runSla(final long admin)throws Exception{
        final int[] count={0};Database.tx(c->{int reminder=config(c,"APPOINTMENT_REMINDER_HOURS",12);Timestamp now=Timestamp.valueOf(LocalDateTime.now());Timestamp until=Timestamp.valueOf(LocalDateTime.now().plusHours(reminder));List<Map<String,Object>> apps=Database.query(c,"SELECT a.appointment_id,a.customer_id,a.engineer_id,es.service_date,st.start_time FROM appointment a JOIN engineer_schedule es ON es.schedule_id=a.schedule_id JOIN standard_time_slot st ON st.slot_id=es.slot_id WHERE a.status='BOOKED' AND es.service_date BETWEEN CURRENT_DATE AND ?",java.sql.Date.valueOf(until.toLocalDateTime().toLocalDate()));for(Map<String,Object>a:apps){LocalDateTime at=LocalDateTime.of(((java.sql.Date)a.get("service_date")).toLocalDate(),((Time)a.get("start_time")).toLocalTime());if(!at.isBefore(now.toLocalDateTime())&&!at.isAfter(until.toLocalDateTime())){long id=((Number)a.get("appointment_id")).longValue();count[0]+=notifyOnce(c,((Number)a.get("customer_id")).longValue(),"APPOINTMENT_REMINDER","预约即将开始","请准备按约接受维修服务","APPOINTMENT",id);count[0]+=notifyOnce(c,((Number)a.get("engineer_id")).longValue(),"APPOINTMENT_REMINDER","预约即将开始","请按预约时间提供维修服务","APPOINTMENT",id);}}
            int orderHours=config(c,"ORDER_SLA_HOURS",48);Timestamp orderBefore=Timestamp.valueOf(LocalDateTime.now().minusHours(orderHours));for(Map<String,Object>o:Database.query(c,"SELECT order_id,engineer_id FROM repair_order WHERE order_status IN ('REPAIRING','WAITING_PARTS','REWORK') AND created_at<?",orderBefore)){count[0]+=notifyOnce(c,((Number)o.get("engineer_id")).longValue(),"ORDER_OVERDUE","维修工单处理超时","请尽快更新维修进度","ORDER",((Number)o.get("order_id")).longValue());}
            int partHours=config(c,"PART_REVIEW_SLA_HOURS",8);Timestamp partBefore=Timestamp.valueOf(LocalDateTime.now().minusHours(partHours));List<Map<String,Object>> managers=Database.query(c,"SELECT user_id FROM system_user WHERE role_type='WAREHOUSE' AND status='ACTIVE'");for(Map<String,Object>p:Database.query(c,"SELECT part_request_id FROM part_request WHERE status='PENDING' AND created_at<?",partBefore))for(Map<String,Object>m:managers)count[0]+=notifyOnce(c,((Number)m.get("user_id")).longValue(),"PART_REVIEW_OVERDUE","配件申请审核超时","请尽快处理待审核申请","PART_REQUEST",((Number)p.get("part_request_id")).longValue());log(c,admin,"RUN_SLA","SYSTEM",0,"生成通知："+count[0]);});return count[0];
    }
    private int config(Connection c,String key,int fallback)throws Exception{Map<String,Object>r=Database.one(c,"SELECT config_value FROM system_config WHERE config_key=?",key);try{return r==null?fallback:Integer.parseInt(String.valueOf(r.get("config_value")));}catch(Exception e){return fallback;}}
    private int notifyOnce(Connection c,long user,String type,String title,String content,String business,long id)throws Exception{Map<String,Object>exists=Database.one(c,"SELECT notification_id FROM notification WHERE receiver_id=? AND notification_type=? AND related_business_type=? AND related_business_id=?",user,type,business,id);if(exists!=null)return 0;notify(c,user,type,title,content,business,id);return 1;}
    private void notify(Connection c,long user,String type,String title,String content,String business,long id)throws Exception{Database.update(c,"INSERT INTO notification(receiver_id,notification_type,title,content,related_business_type,related_business_id) VALUES(?,?,?,?,?,?)",user,type,title,content,business,id);}
    private void log(Connection c,long user,String op,String type,long id,String text)throws Exception{Database.update(c,"INSERT INTO operation_log(user_id,operation_type,business_type,business_id,description) VALUES(?,?,?,?,?)",user,op,type,id,text);}
}
